trigger:
- main

pool:
  name: Default
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 
variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'